<?php

namespace App\Database\Seeds;

use CodeIgniter\Database\Seeder;

class MenuSeeder extends Seeder
{
    public function run()
    {
        $now = date('Y-m-d H:i:s');
        $data = [
            [
                'id'              => 1,
                'category_id'     => 1,
                'name'            => 'Tinutuan Original Manado Spesial',
                'slug'            => 'tinutuan-original-manado-spesial',
                'description'     => 'Bubur Manado autentik yang dimasak perlahan dengan labu kuning manis (sambiki), kangkung segar, bayam hijau, jagung manis pipil, dan aroma semerbak daun kemangi alami.',
                'price'           => 22000.00,
                'spiciness_level' => 0,
                'ingredients'     => 'Beras pulen, labu kuning manis, kangkung, bayam, jagung manis pipil, daun kemangi segar, sereh, daun bawang, garam laut.',
                'calories'        => 280,
                'is_favorite'     => 1,
                'is_available'    => 1,
                'image'           => 'tinutuan_original.jpg',
                'created_at'      => $now,
                'updated_at'      => $now,
            ],
            [
                'id'              => 2,
                'category_id'     => 1,
                'name'            => 'Tinutuan Cakalang Fufu Suwir',
                'slug'            => 'tinutuan-cakalang-fufu-suwir',
                'description'     => 'Perpaduan sempurna kelembutan bubur sayur Tinutuan dengan suwiran gurih daging ikan cakalang asap khas Bitung Sulawesi Utara serta taburan bawang merah goreng renyah.',
                'price'           => 32000.00,
                'spiciness_level' => 1,
                'ingredients'     => 'Beras pilihan, labu kuning, kangkung, jagung, cakalang fufu asap, kemangi, sambal dabu-dabu iris segar, bawang merah goreng.',
                'calories'        => 390,
                'is_favorite'     => 1,
                'is_available'    => 1,
                'image'           => 'tinutuan_cakalang.jpg',
                'created_at'      => $now,
                'updated_at'      => $now,
            ],
            [
                'id'              => 3,
                'category_id'     => 1,
                'name'            => 'Tinutuan Sambal Roa Komplit',
                'slug'            => 'tinutuan-sambal-roa-komplit',
                'description'     => 'Sajian Tinutuan bagi pecinta rasa berani! Ditemani sambal roa asap khas Minahasa yang pedas gurih menendang, memberikan sensasi hangat aromatik khas Sulawesi.',
                'price'           => 35000.00,
                'spiciness_level' => 3,
                'ingredients'     => 'Bubur sayur Manado, labu kuning manis, bayam, kangkung, jagung manis, sambal ikan roa asap, perkedel jagung, kemangi segar.',
                'calories'        => 410,
                'is_favorite'     => 1,
                'is_available'    => 1,
                'image'           => 'tinutuan_sambal_roa.jpg',
                'created_at'      => $now,
                'updated_at'      => $now,
            ],
            [
                'id'              => 4,
                'category_id'     => 1,
                'name'            => 'Tinutuan Seafood Kuah Kuning',
                'slug'            => 'tinutuan-seafood-kuah-kuning',
                'description'     => 'Kreasi modern premium mengangkat sajian khas pesisir Manado. Menghadirkan udang windu segar dan olahan ikan laut berpadu gurihnya rempah kuah kunyit aromatik.',
                'price'           => 38000.00,
                'spiciness_level' => 2,
                'ingredients'     => 'Beras pulen, udang segar pilihan, potongan ikan laut segar, rempah kunyit dan serai, labu kuning, sayur kangkung, kemangi aromatik.',
                'calories'        => 420,
                'is_favorite'     => 0,
                'is_available'    => 1,
                'image'           => 'tinutuan_seafood.jpg',
                'created_at'      => $now,
                'updated_at'      => $now,
            ],
            [
                'id'              => 5,
                'category_id'     => 2,
                'name'            => 'Paket Komplit Tinutuan Juara',
                'slug'            => 'paket-komplit-tinutuan-juara',
                'description'     => 'Paket terlaris restoran Aprilianto! Sudah termasuk 1 Porsi Tinutuan Cakalang Fufu Suwir, 2 pcs Perkedel Jagung Crispy hangat, Sambal Roa cup, dan 1 gelas Es Teh Manis Segar.',
                'price'           => 42000.00,
                'spiciness_level' => 2,
                'ingredients'     => '1 porsi Tinutuan Cakalang Fufu, 2 pcs perkedel jagung crispy, 1 cup sambal roa, 1 es teh manis segar aromatik.',
                'calories'        => 560,
                'is_favorite'     => 1,
                'is_available'    => 1,
                'image'           => 'paket_komplit_tinutuan.jpg',
                'created_at'      => $now,
                'updated_at'      => $now,
            ],
            [
                'id'              => 6,
                'category_id'     => 2,
                'name'            => 'Paket Sarapan Sultan Manado',
                'slug'            => 'paket-sarapan-sultan-manado',
                'description'     => 'Kombinasi sarapan mewah penuh energi khas Minahasa: Tinutuan Komplit, Cakalang Fufu, Perkedel Nike Danau Tondano, Pisang Goroho Crispy, dan Es Brenebon Mini.',
                'price'           => 48000.00,
                'spiciness_level' => 2,
                'ingredients'     => 'Tinutuan komplit, suwiran cakalang asap, perkedel ikan nike Tondano, pisang goroho, sambal roa, es brenebon mini.',
                'calories'        => 620,
                'is_favorite'     => 0,
                'is_available'    => 1,
                'image'           => 'paket_sarapan_sultan.jpg',
                'created_at'      => $now,
                'updated_at'      => $now,
            ],
            [
                'id'              => 7,
                'category_id'     => 3,
                'name'            => 'Perkedel Jagung Manado Crispy (Isi 3)',
                'slug'            => 'perkedel-jagung-manado-crispy',
                'description'     => 'Teman setia santap Tinutuan. Terbuat dari pipilan jagung manis segar berbumbu rempah harum, digoreng garing renyah di luar namun lembut di dalam dengan cocolan dabu-dabu.',
                'price'           => 18000.00,
                'spiciness_level' => 1,
                'ingredients'     => 'Jagung manis segar, daun bawang, seledri, bumbu rempah bawang putih ketumbar, cabai rawit dabu-dabu.',
                'calories'        => 240,
                'is_favorite'     => 1,
                'is_available'    => 1,
                'image'           => 'perkedel_jagung.jpg',
                'created_at'      => $now,
                'updated_at'      => $now,
            ],
            [
                'id'              => 8,
                'category_id'     => 3,
                'name'            => 'Pisang Goreng Goroho Sambal Roa',
                'slug'            => 'pisang-goreng-goroho-sambal-roa',
                'description'     => 'Camilan legendaris Sulawesi Utara! Irisan tipis pisang goroho muda yang digoreng garing gurih renyah tanpa rasa manis berlebih, dicocol dengan pedas gurihnya sambal roa.',
                'price'           => 24000.00,
                'spiciness_level' => 3,
                'ingredients'     => 'Pisang goroho muda pilihan, minyak kelapa murni, sambal roa panggang, garam himalaya.',
                'calories'        => 290,
                'is_favorite'     => 1,
                'is_available'    => 1,
                'image'           => 'pisang_goroho.jpg',
                'created_at'      => $now,
                'updated_at'      => $now,
            ],
            [
                'id'              => 9,
                'category_id'     => 4,
                'name'            => 'Es Brenebon Kacang Merah Manado',
                'slug'            => 'es-brenebon-kacang-merah-manado',
                'description'     => 'Pencuci mulut legendaris khas Manado. Kacang merah empuk yang dimasak manis dengan gula aren dan kayu manis, disajikan di atas serutan es dingin bertabur susu kental manis.',
                'price'           => 20000.00,
                'spiciness_level' => 0,
                'ingredients'     => 'Kacang merah empuk, es serut, susu kental manis, sirup merah vanila khas Manado, bubuk kayu manis, gula aren asli.',
                'calories'        => 260,
                'is_favorite'     => 1,
                'is_available'    => 1,
                'image'           => 'es_brenebon.jpg',
                'created_at'      => $now,
                'updated_at'      => $now,
            ],
            [
                'id'              => 10,
                'category_id'     => 4,
                'name'            => 'Klappertaart Panggang Mini Autentik',
                'slug'            => 'klappertaart-panggang-mini-autentik',
                'description'     => 'Dessert warisan kolonial khas Manado dengan tekstur super lembut kaya kelapa muda segar, susu murni, mentega gurih, serta taburan kismis, kenari panggang, dan bubuk kayu manis harum.',
                'price'           => 25000.00,
                'spiciness_level' => 0,
                'ingredients'     => 'Kelapa muda segar, susu sapi murni, mentega, kuning telur, kismis, kenari Manado panggang, kayu manis bubuk.',
                'calories'        => 310,
                'is_favorite'     => 0,
                'is_available'    => 1,
                'image'           => 'klappertaart.jpg',
                'created_at'      => $now,
                'updated_at'      => $now,
            ],
        ];

        $this->db->table('menus')->insertBatch($data);
    }
}
